// embedded_files.h
// This is a placeholder header included by the firmware. The real header is generated by
// tools/embed_static.js. If you run the script it will overwrite this file with
// the full asset arrays.

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  const char* url;
  const uint8_t* data;
  const size_t size;
  const char* contentType;
  const bool gzip;
} EmbeddedFile;

// If you run tools/embed_static.js it will populate these.
static const EmbeddedFile embedded_files[] = {
  // empty placeholder
};

static const size_t embedded_files_count = 0;

#ifdef __cplusplus
}
#endif
