#!/usr/bin/env node
// embed_static.js
// Usage: node embed_static.js --input <dir> --output <file> [--prefix /] [--gzip]
// This script walks the input directory and writes a C header with PROGMEM arrays
// and a manifest mapping URL paths to the data arrays. It gzips files when --gzip
// is specified to reduce flash use and adds Content-Encoding: gzip header in the map.

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

function walk(dir) {
  const out = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      const sub = walk(full).map(p => ({ path: path.posix.join(name, p.path), dataPath: p.dataPath, full: p.full }));
      out.push(...sub);
    } else if (stat.isFile()) {
      out.push({ path: name, full });
    }
  }
  return out;
}

function allFiles(dir, base = '') {
  let files = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    const rel = base ? `${base}/${name}` : name;
    if (stat.isDirectory()) {
      files = files.concat(allFiles(full, rel));
    } else {
      files.push({ path: rel.replace(/\\\\/g, '/'), full });
    }
  }
  return files;
}

function contentTypeFor(pathname) {
  if (pathname.endsWith('.html')) return 'text/html';
  if (pathname.endsWith('.js')) return 'application/javascript';
  if (pathname.endsWith('.css')) return 'text/css';
  if (pathname.endsWith('.json')) return 'application/json';
  if (pathname.endsWith('.svg')) return 'image/svg+xml';
  if (pathname.endsWith('.png')) return 'image/png';
  if (pathname.endsWith('.jpg') || pathname.endsWith('.jpeg')) return 'image/jpeg';
  if (pathname.endsWith('.ico')) return 'image/x-icon';
  if (pathname.endsWith('.woff2')) return 'font/woff2';
  return 'application/octet-stream';
}

function toIdentifier(p) {
  return p.replace(/[^a-zA-Z0-9]/g, '_');
}

function usage() {
  console.log('Usage: node embed_static.js --input <dir> --output <file> [--prefix /] [--gzip]');
  process.exit(1);
}

const argv = process.argv.slice(2);
let inputDir = null;
let outputFile = null;
let prefix = '/';
let doGzip = false;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--input') inputDir = argv[++i];
  else if (a === '--output') outputFile = argv[++i];
  else if (a === '--prefix') prefix = argv[++i];
  else if (a === '--gzip') doGzip = true;
  else usage();
}
if (!inputDir || !outputFile) usage();
if (!fs.existsSync(inputDir)) {
  console.error('Input directory not found:', inputDir);
  process.exit(2);
}

const files = allFiles(inputDir).map(f => ({ url: path.posix.join(prefix, f.path), full: f.full }));

let out = '';
out += '// GENERATED by embed_static.js - do not edit by hand\n';
out += '#pragma once\n\n#include <stdint.h>\n#include <stddef.h>\n\n#ifdef __cplusplus\nextern "C" {\n#endif\n\ntypedef struct {\n  const char* url;\n  const uint8_t* data;\n  const size_t size;\n  const char* contentType;\n  const bool gzip;\n} EmbeddedFile;\n\n';

const arrays = [];
for (const f of files) {
  let data = fs.readFileSync(f.full);
  let gz = false;
  if (doGzip) {
    const gzdata = zlib.gzipSync(data, { level: 9 });
    if (gzdata.length < data.length) {
      data = gzdata;
      gz = true;
    }
  }
  const id = toIdentifier(f.url);
  const contentType = contentTypeFor(f.url);
  out += `// ${f.url} -> ${path.relative(process.cwd(), f.full)}\n`;
  out += `static const uint8_t ${id}_data[] PROGMEM = {\n`;
  const bytes = Array.from(data);
  for (let i = 0; i < bytes.length; i += 12) {
    const chunk = bytes.slice(i, i + 12).map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ');
    out += '  ' + chunk + ',\n';
  }
  out += '};\n';
  out += `static const size_t ${id}_size = ${bytes.length};\n\n`;
  arrays.push({ id, url: f.url, contentType, gzip: gz });
}

out += `static const EmbeddedFile embedded_files[] = {\n`;
for (const a of arrays) {
  out += `  { "${a.url}", ${a.id}_data, ${a.id}_size, "${a.contentType}", ${a.gzip ? 'true' : 'false'} },\n`;
}
out += '};\n\n';
out += `static const size_t embedded_files_count = sizeof(embedded_files) / sizeof(embedded_files[0]);\n\n`;

out += '#ifdef __cplusplus\n}\n#endif\n';

fs.writeFileSync(outputFile, out, 'utf8');
console.log('Wrote', outputFile, 'with', arrays.length, 'files (gzip=', doGzip, ')');
